// libs/api-client/examples/vue-example.vue
<template>
  <div class="books-app">
    <!-- Login Form -->
    <form @submit.prevent="login" v-if="!user">
      <input
        v-model="email"
        type="email"
        placeholder="Email"
        required
      />
      <input
        v-model="password"
        type="password"
        placeholder="Password"
        required
      />
      <button type="submit" :disabled="loading">
        {{ loading ? 'Logging in...' : 'Login' }}
      </button>
      <div v-if="error" class="error">{{ error }}</div>
    </form>

    <!-- User Dashboard -->
    <div v-if="user">
      <h2>Welcome, {{ user.email }}!</h2>
      <button @click="logout">Logout</button>
      
      <!-- Books List -->
      <div class="books">
        <h3>Books</h3>
        <div v-for="book in books" :key="book.id" class="book">
          <h4>{{ book.title }}</h4>
          <p>{{ book.description }}</p>
          <button @click="addToBookshelf(book.id)">
            Add to Bookshelf
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { BooksApiClient } from '../src/index';

const api = new BooksApiClient({
  baseURL: process.env.VUE_APP_API_URL || 'http://localhost:5000'
});

const user = ref(null);
const books = ref([]);
const email = ref('');
const password = ref('');
const loading = ref(false);
const error = ref('');

const login = async () => {
  loading.value = true;
  error.value = '';
  
  try {
    await api.login({
      email: email.value,
      password: password.value
    });
    
    user.value = await api.users.getMe();
    await fetchBooks();
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Login failed';
  } finally {
    loading.value = false;
  }
};

const logout = async () => {
  await api.logout();
  user.value = null;
  books.value = [];
};

const fetchBooks = async () => {
  try {
    books.value = await api.books.getAll({ limit: 10 });
  } catch (err) {
    console.error('Failed to fetch books:', err);
  }
};

const addToBookshelf = async (bookId: string) => {
  try {
    await api.bookshelf.add(bookId);
    alert('Book added to bookshelf!');
  } catch (err) {
    alert('Failed to add book to bookshelf');
  }
};

onMounted(() => {
  // Try to load user if already authenticated
  api.users.getMe().then(userData => {
    user.value = userData;
    fetchBooks();
  }).catch(() => {
    // User not authenticated
  });
});
</script>

<style scoped>
.books-app {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.book {
  border: 1px solid #ddd;
  padding: 15px;
  margin: 10px 0;
  border-radius: 5px;
}

.error {
  color: red;
  margin: 10px 0;
}
</style>

// libs/api-client/examples/react-example.tsx
import React, { useState, useEffect } from 'react';
import { BooksApiClient } from '../src/index';

const api = new BooksApiClient({
  baseURL: process.env.REACT_APP_API_URL || 'http://localhost:5000',
});

// Authentication component
export const LoginForm: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const tokens = await api.login({ email, password });
      console.log('Login successful:', tokens);
      // Handle successful login (e.g., redirect, update state)
    } catch (err: any) {
      setError(err.response?.data?.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleLogin}>
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="Email"
        required
      />
      <input
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Password"
        required
      />
      {error && <div className="error">{error}</div>}
      <button type="submit" disabled={loading}>
        {loading ? 'Logging in...' : 'Login'}
      </button>
    </form>
  );
};

// Books list component
export const BooksList: React.FC = () => {
  const [books, setBooks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchBooks = async () => {
      try {
        const data = await api.books.getAll({ limit: 20 });
        setBooks(data);
      } catch (err: any) {
        setError('Failed to load books');
      } finally {
        setLoading(false);
      }
    };

    fetchBooks();
  }, []);

  if (loading) return <div>Loading books...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <div>
      <h2>Books</h2>
      {books.map((book: any) => (
        <div key={book.id}>
          <h3>{book.title}</h3>
          <p>{book.description}</p>
        </div>
      ))}
    </div>
  );
};

// Book detail component
export const BookDetail: React.FC<{ slug: string }> = ({ slug }) => {
  const [book, setBook] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchBook = async () => {
      try {
        const data = await api.books.getOverview(slug);
        setBook(data);
      } catch (err) {
        console.error('Failed to load book:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchBook();
  }, [slug]);

  if (loading) return <div>Loading...</div>;
  if (!book) return <div>Book not found</div>;

  return (
    <div>
      <h1>{(book as any).title}</h1>
      <p>{(book as any).description}</p>
      {/* Render other book details */}
    </div>
  );
};
